//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exigences3000.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jalon
    {
        public int id { get; set; }
        public Nullable<int> id_projet { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<System.DateTime> date_prevue { get; set; }
        public Nullable<System.DateTime> date_livraison { get; set; }
    
        public virtual Projet Projet { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
