//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exigence3000.MVC.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jalon : IEnumerable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jalon()
        {
            this.Tache = new HashSet<Tache>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_projet { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<System.DateTime> date_prevue { get; set; }
        public Nullable<System.DateTime> date_livraison { get; set; }
    
        public virtual Projet Projet { get; set; }
        public virtual Responsable Responsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tache> Tache { get; set; }
    }
}
